name: "urban_mobility"
version: "1.0.0"
config-version: 2

profile: "urban_mobility"

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  urban_mobility:
    staging:
      +materialized: view
      +schema: gold
    dim:
      +materialized: table
      +schema: gold
    fact:
      +materialized: table
      +schema: gold
    view:
      +schema: gold
